GridLayout:
    cols: 1

    Label:
        id: moeda1
        text: "1º texto"
        color: 1, 0, 0, 1  # Vermelho (R, G, B, A)

    Label:
        id: moeda2
        text: "2º texto"
        color: 0, 1, 0, 1  # Verde (R, G, B, A)

    Label:
        id: moeda3
        text: "3º texto"
        color: 0, 0, 1, 1  # Azul (R, G, B, A)

    Label:
        id: moeda4
        text: "4º texto"
        color: 1, 1, 0, 1  # Amarelo (R, G, B, A)
